const fs = require('fs');
const path = require('path');

const chainId = process.argv[2];

if (!chainId) {
    console.error("❌ Please provide a chainId! Example: node format_deployments.js 31337");
    process.exit(1);
}

const frontendPath = path.join(__dirname, '../frontend/src/deployments.json');

const tempPath = './temp_addresses.json';
if (!fs.existsSync(tempPath)) {
    console.error("❌ temp_addresses.json not found. Did you run `forge script` first?");
    process.exit(1);
}
const addresses = JSON.parse(fs.readFileSync(tempPath, 'utf8'));

// Read ABIs generated by Forge
const tokenArtifact = JSON.parse(fs.readFileSync('./out/AgentToken.sol/AgentToken.json', 'utf8'));
const agentraArtifact = JSON.parse(fs.readFileSync('./out/Agentra.sol/Agentra.json', 'utf8'));
const reactorArtifact = JSON.parse(fs.readFileSync('./out/AgentraReactor.sol/AgentraReactor.json', 'utf8'));

let deployments = {};
if (fs.existsSync(frontendPath)) {
    const rawData = fs.readFileSync(frontendPath, 'utf8').trim();
    if (rawData) {
        try { deployments = JSON.parse(rawData); } 
        catch (e) { deployments = {}; }
    }
}

deployments[chainId] = {
    AgentToken: { address: addresses.AgentToken, abi: "%%AGENT_TOKEN_ABI%%" },
    Agentra: { address: addresses.Agentra, abi: "%%AGENTRA_ABI%%" },
    AgentraReactor: { address: addresses.AgentraReactor, abi: "%%REACTOR_ABI%%" }
};

let outputJson = JSON.stringify(deployments, null, 2);

outputJson = outputJson.replace('"%%AGENT_TOKEN_ABI%%"', JSON.stringify(tokenArtifact.abi));
outputJson = outputJson.replace('"%%AGENTRA_ABI%%"', JSON.stringify(agentraArtifact.abi));
outputJson = outputJson.replace('"%%REACTOR_ABI%%"', JSON.stringify(reactorArtifact.abi));

fs.writeFileSync(frontendPath, outputJson);
fs.unlinkSync('./temp_addresses.json'); 
console.log(`✅ Deployments (Token, Agentra, Reactor) auto-synced to frontend for Chain ID ${chainId}`);